version: "3.8"

services:
  app:
    container_name: schedule-buddy-prod
    image: schedule-buddy-prod
    build:
      context: .
      dockerfile: dockerfile
      args:
        - VITE_FIREBASE_API_KEY= AIzaSyCXK9h_wnhNHvnaTZ3FREI4BDDOICPfr6g
        - VITE_FIREBASE_AUTH_DOMAIN=schedule-buddy-app.firebaseapp.com
        - VITE_FIREBASE_DATABASE_URL=https://your-dev-app.firebaseio.com
        - VITE_FIREBASE_PROJECT_ID=schedule-buddy-app
        - VITE_FIREBASE_STORAGE_BUCKET=schedule-buddy-app.appspot.com
        - VITE_FIREBASE_MESSAGING_SENDER_ID=505046968992
        - VITE_FIREBASE_APP_ID=1:505046968992:web:1582654123e27ee9dd37c5
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
